[build]
  command = "npm run build"
  publish = "public"

[[scheduled]]
  cron = "0 10 * * 1"
  branch = "main"

[functions]
  directory = "src/api"

[[redirects]]
  from = "/favicon.ico"
  to = "/favicon-32x32.png"
  status = 301
  force = true
